file:
  input: coffee-list.csv
spring:
  datasource:
    url: jdbc:mysql://awsmariadb.cdlzwb1dr7j4.ap-northeast-2.rds.amazonaws.com:3306/test?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: org.mariadb.jdbc.Driver
    username: only9984
    password: 5523978co
  batch:
    initialize-schema: always
server:
  port: 8080